# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"#\n\nRunRequest\x12\x15\n\rcommands_file\x18\x01 \x01(\t\":\n\x0bRunResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x05\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"-\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07service\x18\x02 \x01(\t2s\n\x0c\x41gentGateway\x12,\n\x03Run\x12\x11.agent.RunRequest\x1a\x12.agent.RunResponse\x12\x35\n\x06Health\x12\x14.agent.HealthRequest\x1a\x15.agent.HealthResponse2I\n\x10InventoryService\x12\x35\n\x06Health\x12\x14.agent.HealthRequest\x1a\x15.agent.HealthResponse2E\n\x0cResultWriter\x12\x35\n\x06Health\x12\x14.agent.HealthRequest\x1a\x15.agent.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST']._serialized_start=22
  _globals['_RUNREQUEST']._serialized_end=57
  _globals['_RUNRESPONSE']._serialized_start=59
  _globals['_RUNRESPONSE']._serialized_end=117
  _globals['_HEALTHREQUEST']._serialized_start=119
  _globals['_HEALTHREQUEST']._serialized_end=134
  _globals['_HEALTHRESPONSE']._serialized_start=136
  _globals['_HEALTHRESPONSE']._serialized_end=181
  _globals['_AGENTGATEWAY']._serialized_start=183
  _globals['_AGENTGATEWAY']._serialized_end=298
  _globals['_INVENTORYSERVICE']._serialized_start=300
  _globals['_INVENTORYSERVICE']._serialized_end=373
  _globals['_RESULTWRITER']._serialized_start=375
  _globals['_RESULTWRITER']._serialized_end=444
# @@protoc_insertion_point(module_scope)
